### PR TITLE
Update pyproject.toml by updating version of tenacity

### PR DESCRIPTION
**Pull request by Anindyadeep**
Actually the problem is, due to tenacity version being strict and not updated it was hard to integrate with other packages. So this PR tries to resolve that.

### CODE REVIEW

**Comment by Anindyadeep** [comment]
Hi @penguine-ip, I updated the pyproject by updating the tenacity version. We were facing some dependency conflict issues, while using deepeval inside our project. So this PR tries to update tenacity version to avoid conflict.

**Comment by penguine-ip** [comment]
hey @Anindyadeep thanks for the PR, can you update setup.py as well? We use poetry for internal dev and setup.py for release, so updating poetry alone won't help your team

**Comment by Anindyadeep** [comment]
> hey @Anindyadeep thanks for the PR, can you update setup.py as well? We use poetry for internal dev and setup.py for release, so updating poetry alone won't help your team

Thanks @penguine-ip, I updated setup.py

**Comment by Anindyadeep** [comment]
Hi lemme know if this can be merged, thanks

**Comment by rohitgr7** [comment]
@penguine-ip can we merge this PR? We are also facing dependency issues due to tenacity version here,

**Comment by penguine-ip** [comment]
@Anindyadeep @rohitgr7 done!

**Comment by rohitgr7** [comment]
@penguine-ip thanks! Btw when is it going to be released??

**Comment by rohitgr7** [comment]
@penguine-ip when is it going to be released??

**Comment by penguine-ip** [comment]
@rohitgr7 i believe it already is

**Pull request merged**
