### PR TITLE
Feature: Add a metrics class to organize atomic set of re-usable metrics 

### PR DESCRIPTION
**Pull request by Anindyadeep**
Solves issue #238

### CODE REVIEW

**Comment by penguine-ip** [comment]
I was thinking to use Calculator (eg StatisticalCalculator) instead of using the word Metrics since this might be confusing in the docs. So a calculator calculates one of these scores that is used in a metric.

**Comment by Anindyadeep** [comment]
Does it make more sense to rename the file as `metrics.py` or `metrics_base.py` ? instead of `metrics_calculator.py`?

**Comment by penguine-ip** [comment]
I think calculator is more fitting since it calculates a score, whereas metrics has an 1) evaluation criteria and 2) passing criteria. It could live in metrics/scores/calculator.py, with `StatisticalCalcuator` and `ModelBasedCalculator` respectively.

**Comment by Anindyadeep** [comment]
Yeah that can work, creating the changes

**Comment by penguine-ip** [comment]
Thanks!

**Pull request merged**
