### PR TITLE
Deprecate Factual Consistency

### PR DESCRIPTION
**Pull request by penguine-ip**

### CODE REVIEW

**Comment by rohinish404** [comment]
Why this metric was deprecated?

**Comment by penguine-ip** [comment]
@rohinish404 Metric wasn't very accurate, and we rolled out a `HallucinationMetric` instead

**Comment by rohinish404** [comment]
> @rohinish404 Metric wasn't very accurate, and we rolled out a `HallucinationMetric` instead

Is that doing the same thing the factual consistency one did?

**Comment by penguine-ip** [comment]
Yup! What are you trying to evaluate? (RAG or fine-tuned LLMs?)

**Comment by rohinish404** [comment]
> Yup! What are you trying to evaluate? (RAG or fine-tuned LLMs?)

Hmm...im not sure..just trying to write a script which calculates factual consistency of outputs generated using openai api given input and context.

**Comment by rohinish404** [comment]
New to evaluating llms ..so if u can share some useful resources..it'll be helpful

**Comment by penguine-ip** [comment]
@rohinish404 Here is a set of blog posts that gets you started: https://www.confident-ai.com/blog

**Comment by rohinish404** [comment]
> @rohinish404 Here is a set of blog posts that gets you started: https://www.confident-ai.com/blog

Thanks for sharing!! :)

**Comment by rohinish404** [comment]
@penguine-ip thanks for the blogs. They are really awesome. Looking forward to more such awesome blogs in future :)
one ques i have is - why nli models are used for calculating factual consistency or hallucination?

**Comment by penguine-ip** [comment]
@rohinish404 Thanks! Please join our discord for more discussions on evaluation :) https://discord.com/invite/a3K9c8GRGt

As for NLI models, they offer some insight into contradictions which is nice, although we're shifting towards using LLMs instead. Also releasing another post on that soon

**Comment by rohinish404** [comment]
> @rohinish404 Thanks! Please join our discord for more discussions on evaluation :) https://discord.com/invite/a3K9c8GRGt
> 
> As for NLI models, they offer some insight into contradictions which is nice, although we're shifting towards using LLMs instead. Also releasing another post on that soon

Hey, thanks for the invite. Just joined it! I'll ask my ques there! :)

**Pull request merged**
