### PR TITLE
Feature: Added Faithfulness score. 

### PR DESCRIPTION
**Pull request by Anindyadeep**
This PR addresses issue: #246. This includes:

- adding faithufulness score in deepeval package
- adding corresponding tests 
- updating the requirements file

Please note that `allennlp` is one of the libraries put under the requirements file. This library is no more maintained. However, this library is required in the one of the implementation parts of SummaC model implementation.

### CODE REVIEW

**Comment by penguine-ip** [comment]
Some issues with the latest dependencies, might have to find another workaround

**Comment by Anindyadeep** [comment]
Yes, I am trying to see any alternative paths here :)

**Comment by penguine-ip** [comment]
Thanks!

**Comment by Anindyadeep** [comment]
@penguine-ip things are working, ready for merge here, I believe. Also thanks @Vasilije1990 for the awesome fix in the dependencies side.

**Comment by penguine-ip** [comment]
@Anindyadeep Thanks! I might start a new section on the docs for scores, welcome any suggestions on how to abstract things

**Comment by Anindyadeep** [comment]
> @Anindyadeep Thanks! I might start a new section on the docs for scores, welcome any suggestions on how to abstract things

Yeah, even I am also up for creating the docs. Just one decision point I need, Should we start docs as a parallel thread, or should we add the other docs and start docs?

**Pull request merged**
