### PR TITLE
Keep local results file if not logged in

### PR DESCRIPTION
**Pull request by Andrea23Romano**
Local results file is deleted even if not logged in. In that case it could be useful to keep it.

### CODE REVIEW

**Comment by penguine-ip** [comment]
@Andrea23Romano thanks for the commit, I'm going to make this conditional on an environment variable to not pollute a user's directory

**Comment by Andrea23Romano** [comment]
> @Andrea23Romano thanks for the commit, I'm going to make this conditional on an environment variable to not pollute a user's directory

I was thinking about adding one in deepeval.constants, is that ok?

**Comment by penguine-ip** [comment]
@Andrea23Romano if that's the case and i'm not mistaken, a user will have to edit some deepeval source code to turn on/off saving the file, is that correct?

**Comment by Andrea23Romano** [comment]
I don't think so, the user could simply add a statement like
```
deepeval.constants.PYTEST_LOCAL_RESULTS_FOLDER=<path>
```
in the test file. Could be None by default and, if not None, the file would be saved in that folder. I'm going to try it later and push it to this branch if everything works.

**Comment by penguine-ip** [comment]
@Andrea23Romano can you please make it an env variable instead, constants are meant to be accessed by deepeval internally

**Comment by Andrea23Romano** [comment]
Sure!

**Comment by penguine-ip** [comment]
@Andrea23Romano thanks! appreciate it

**Comment by Andrea23Romano** [comment]
@penguine-ip env variable and documentation example added. Let me know if it's ok or if I should change something!

**Comment by penguine-ip** [comment]
@Andrea23Romano Looks good, going to merge after the tests completes, thanks! 😊

**Comment by penguine-ip** [comment]
@Andrea23Romano I dont see why but deepeval login is failing in .github/workflows/deepeval-results.yml, any idea?

**Comment by Andrea23Romano** [comment]
No idea, going to check it later.

**Comment by Andrea23Romano** [comment]
Something's wrong with the action. In setup job "secret source" is set to None, so it can't find the deepeval api key. I'm not a github actions expert, but after some search seems like the secrets are not available for actions triggered by external forks, probably because of some "first time" PR restrictions you can probably modify. Check this, could be useful: https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#configuring-required-approval-for-workflows-from-public-forks

**Comment by penguine-ip** [comment]
@Andrea23Romano Hey, thanks for submitting the PR, join our discord if you haven't already, we're trying to build up the contributors community!

**Pull request merged**
